"""add immutable afe snapshot framework

Revision ID: 20260813_0007
Revises: 20260813_0006
Create Date: 2026-08-13 06:27:17.614570
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260813_0007"
down_revision: str | None = "20260813_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "afe_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("afe_number", sa.String(length=100), nullable=False),
        sa.Column("snapshot_type", sa.String(length=20), server_default="baseline", nullable=False),
        sa.Column("estimate_version_id", sa.Uuid(), nullable=False),
        sa.Column("calculation_run_id", sa.Uuid(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("estimate_code", sa.String(length=100), nullable=False),
        sa.Column("estimate_title", sa.String(length=255), nullable=False),
        sa.Column("requirement_code", sa.String(length=100), nullable=False),
        sa.Column("project_code", sa.String(length=100), nullable=False),
        sa.Column("well_code", sa.String(length=100), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("engine_version", sa.String(length=50), nullable=False),
        sa.Column("rule_set_version", sa.String(length=50), nullable=False),
        sa.Column("base_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("contingency_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("escalation_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("source_snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "snapshot_type = 'baseline'", name=op.f("ck_afe_snapshots_baseline_only")
        ),
        sa.ForeignKeyConstraint(
            ["calculation_run_id"],
            ["estimate_calculations.id"],
            name=op.f("fk_afe_snapshots_calculation_run_id_estimate_calculations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            ["estimate_versions.id"],
            name=op.f("fk_afe_snapshots_estimate_version_id_estimate_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_afe_snapshots")),
        sa.UniqueConstraint("estimate_version_id", name="uq_afe_snapshots_estimate_version"),
    )
    op.create_index(
        op.f("ix_afe_snapshots_afe_number"), "afe_snapshots", ["afe_number"], unique=True
    )
    op.create_index(
        op.f("ix_afe_snapshots_calculation_run_id"),
        "afe_snapshots",
        ["calculation_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_afe_snapshots_estimate_version_id"),
        "afe_snapshots",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_table(
        "afe_snapshot_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("estimate_version_id", sa.Uuid(), nullable=False),
        sa.Column("resulting_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("requested_reference", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("eligibility_snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('completed','blocked','denied','failed')",
            name=op.f("ck_afe_snapshot_attempts_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            ["estimate_versions.id"],
            name=op.f("fk_afe_snapshot_attempts_estimate_version_id_estimate_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resulting_snapshot_id"],
            ["afe_snapshots.id"],
            name=op.f("fk_afe_snapshot_attempts_resulting_snapshot_id_afe_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_afe_snapshot_attempts")),
    )
    op.create_index(
        op.f("ix_afe_snapshot_attempts_estimate_version_id"),
        "afe_snapshot_attempts",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_afe_snapshot_attempts_resulting_snapshot_id"),
        "afe_snapshot_attempts",
        ["resulting_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_afe_snapshot_attempts_status"), "afe_snapshot_attempts", ["status"], unique=False
    )
    op.create_index(
        "ix_afe_snapshot_attempts_version_created",
        "afe_snapshot_attempts",
        ["estimate_version_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "afe_snapshot_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("afe_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("source_estimate_item_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("item_code", sa.String(length=100), nullable=False),
        sa.Column("item_description", sa.String(length=255), nullable=False),
        sa.Column("item_type", sa.String(length=30), nullable=False),
        sa.Column("cost_code", sa.String(length=100), nullable=False),
        sa.Column("cost_category_code", sa.String(length=100), nullable=True),
        sa.Column("vendor_code", sa.String(length=100), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_code", sa.String(length=50), nullable=False),
        sa.Column("rate_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("rate_currency_code", sa.String(length=3), nullable=True),
        sa.Column("base_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("contingency_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("escalation_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "line_number >= 1", name=op.f("ck_afe_snapshot_lines_positive_line_number")
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_afe_snapshot_lines_non_negative_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["afe_snapshot_id"],
            ["afe_snapshots.id"],
            name=op.f("fk_afe_snapshot_lines_afe_snapshot_id_afe_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_afe_snapshot_lines")),
        sa.UniqueConstraint("afe_snapshot_id", "line_number", name="uq_afe_snapshot_lines_number"),
    )
    op.create_index(
        op.f("ix_afe_snapshot_lines_afe_snapshot_id"),
        "afe_snapshot_lines",
        ["afe_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_afe_snapshot_lines_source_estimate_item_id"),
        "afe_snapshot_lines",
        ["source_estimate_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_afe_snapshot_lines_source_estimate_item_id"), table_name="afe_snapshot_lines"
    )
    op.drop_index(op.f("ix_afe_snapshot_lines_afe_snapshot_id"), table_name="afe_snapshot_lines")
    op.drop_table("afe_snapshot_lines")
    op.drop_index("ix_afe_snapshot_attempts_version_created", table_name="afe_snapshot_attempts")
    op.drop_index(op.f("ix_afe_snapshot_attempts_status"), table_name="afe_snapshot_attempts")
    op.drop_index(
        op.f("ix_afe_snapshot_attempts_resulting_snapshot_id"), table_name="afe_snapshot_attempts"
    )
    op.drop_index(
        op.f("ix_afe_snapshot_attempts_estimate_version_id"), table_name="afe_snapshot_attempts"
    )
    op.drop_table("afe_snapshot_attempts")
    op.drop_index(op.f("ix_afe_snapshots_estimate_version_id"), table_name="afe_snapshots")
    op.drop_index(op.f("ix_afe_snapshots_calculation_run_id"), table_name="afe_snapshots")
    op.drop_index(op.f("ix_afe_snapshots_afe_number"), table_name="afe_snapshots")
    op.drop_table("afe_snapshots")
    # ### end Alembic commands ###
