"""add workflow review framework

Revision ID: 20260813_0006
Revises: 20260812_0005
Create Date: 2026-08-13 06:10:09.168295
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260813_0006"
down_revision: str | None = "20260812_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("record_type", sa.String(length=50), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft','validated','published','retired')",
            name=op.f("ck_workflow_profiles_valid_lifecycle_status"),
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_workflow_profiles_positive_version")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_profiles")),
        sa.UniqueConstraint("code", "version_number", name="uq_workflow_profiles_code_version"),
    )
    op.create_index(op.f("ix_workflow_profiles_code"), "workflow_profiles", ["code"], unique=False)
    op.create_index(
        op.f("ix_workflow_profiles_lifecycle_status"),
        "workflow_profiles",
        ["lifecycle_status"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_profiles_record_lifecycle",
        "workflow_profiles",
        ["record_type", "lifecycle_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_profiles_record_type"), "workflow_profiles", ["record_type"], unique=False
    )
    op.create_table(
        "workflow_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("state_key", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_initial", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_terminal", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_workflow_states_non_negative_sort_order")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["workflow_profiles.id"],
            name=op.f("fk_workflow_states_profile_id_workflow_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_states")),
        sa.UniqueConstraint("profile_id", "state_key", name="uq_workflow_states_profile_key"),
    )
    op.create_index(
        op.f("ix_workflow_states_profile_id"), "workflow_states", ["profile_id"], unique=False
    )
    op.create_table(
        "workflow_transition_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("action_key", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("from_state_key", sa.String(length=50), nullable=False),
        sa.Column("to_state_key", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("requires_comment", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "sort_order >= 0",
            name=op.f("ck_workflow_transition_definitions_non_negative_sort_order"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["workflow_profiles.id"],
            name=op.f("fk_workflow_transition_definitions_profile_id_workflow_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_transition_definitions")),
        sa.UniqueConstraint(
            "profile_id",
            "from_state_key",
            "action_key",
            name="uq_workflow_transitions_profile_from_action",
        ),
    )
    op.create_index(
        op.f("ix_workflow_transition_definitions_profile_id"),
        "workflow_transition_definitions",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "workflow_transition_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transition_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_workflow_transition_roles_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transition_id"],
            ["workflow_transition_definitions.id"],
            name=op.f("fk_workflow_transition_roles_transition_id_workflow_transition_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_transition_roles")),
        sa.UniqueConstraint("transition_id", "role_id", name="uq_workflow_transition_roles_pair"),
    )
    op.create_index(
        op.f("ix_workflow_transition_roles_role_id"),
        "workflow_transition_roles",
        ["role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_transition_roles_transition_id"),
        "workflow_transition_roles",
        ["transition_id"],
        unique=False,
    )
    op.create_table(
        "estimate_review_comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("estimate_version_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            ["estimate_versions.id"],
            name=op.f("fk_estimate_review_comments_estimate_version_id_estimate_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate_review_comments")),
    )
    op.create_index(
        op.f("ix_estimate_review_comments_estimate_version_id"),
        "estimate_review_comments",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_estimate_review_comments_version_created",
        "estimate_review_comments",
        ["estimate_version_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "estimate_workflow_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("estimate_version_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_profile_id", sa.Uuid(), nullable=False),
        sa.Column("current_state_key", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            ["estimate_versions.id"],
            name=op.f("fk_estimate_workflow_instances_estimate_version_id_estimate_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_profile_id"],
            ["workflow_profiles.id"],
            name=op.f("fk_estimate_workflow_instances_workflow_profile_id_workflow_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate_workflow_instances")),
        sa.UniqueConstraint("estimate_version_id", name="uq_estimate_workflow_instances_version"),
    )
    op.create_index(
        op.f("ix_estimate_workflow_instances_current_state_key"),
        "estimate_workflow_instances",
        ["current_state_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_estimate_workflow_instances_estimate_version_id"),
        "estimate_workflow_instances",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_estimate_workflow_instances_workflow_profile_id"),
        "estimate_workflow_instances",
        ["workflow_profile_id"],
        unique=False,
    )
    op.create_table(
        "workflow_transition_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("estimate_version_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_instance_id", sa.Uuid(), nullable=True),
        sa.Column("workflow_profile_id", sa.Uuid(), nullable=True),
        sa.Column("requested_action", sa.String(length=100), nullable=False),
        sa.Column("from_state_key", sa.String(length=50), nullable=True),
        sa.Column("to_state_key", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("context_snapshot", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('completed','blocked','denied','failed')",
            name=op.f("ck_workflow_transition_attempts_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            ["estimate_versions.id"],
            name=op.f("fk_workflow_transition_attempts_estimate_version_id_estimate_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_instance_id"],
            ["estimate_workflow_instances.id"],
            name=op.f(
                "fk_workflow_transition_attempts_workflow_instance_id_estimate_workflow_instances"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_profile_id"],
            ["workflow_profiles.id"],
            name=op.f("fk_workflow_transition_attempts_workflow_profile_id_workflow_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_transition_attempts")),
    )
    op.create_index(
        op.f("ix_workflow_transition_attempts_estimate_version_id"),
        "workflow_transition_attempts",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_transition_attempts_status"),
        "workflow_transition_attempts",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_workflow_transition_attempts_version_created",
        "workflow_transition_attempts",
        ["estimate_version_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_transition_attempts_workflow_instance_id"),
        "workflow_transition_attempts",
        ["workflow_instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_transition_attempts_workflow_profile_id"),
        "workflow_transition_attempts",
        ["workflow_profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_transition_attempts_workflow_profile_id"),
        table_name="workflow_transition_attempts",
    )
    op.drop_index(
        op.f("ix_workflow_transition_attempts_workflow_instance_id"),
        table_name="workflow_transition_attempts",
    )
    op.drop_index(
        "ix_workflow_transition_attempts_version_created", table_name="workflow_transition_attempts"
    )
    op.drop_index(
        op.f("ix_workflow_transition_attempts_status"), table_name="workflow_transition_attempts"
    )
    op.drop_index(
        op.f("ix_workflow_transition_attempts_estimate_version_id"),
        table_name="workflow_transition_attempts",
    )
    op.drop_table("workflow_transition_attempts")
    op.drop_index(
        op.f("ix_estimate_workflow_instances_workflow_profile_id"),
        table_name="estimate_workflow_instances",
    )
    op.drop_index(
        op.f("ix_estimate_workflow_instances_estimate_version_id"),
        table_name="estimate_workflow_instances",
    )
    op.drop_index(
        op.f("ix_estimate_workflow_instances_current_state_key"),
        table_name="estimate_workflow_instances",
    )
    op.drop_table("estimate_workflow_instances")
    op.drop_index(
        "ix_estimate_review_comments_version_created", table_name="estimate_review_comments"
    )
    op.drop_index(
        op.f("ix_estimate_review_comments_estimate_version_id"),
        table_name="estimate_review_comments",
    )
    op.drop_table("estimate_review_comments")
    op.drop_index(
        op.f("ix_workflow_transition_roles_transition_id"), table_name="workflow_transition_roles"
    )
    op.drop_index(
        op.f("ix_workflow_transition_roles_role_id"), table_name="workflow_transition_roles"
    )
    op.drop_table("workflow_transition_roles")
    op.drop_index(
        op.f("ix_workflow_transition_definitions_profile_id"),
        table_name="workflow_transition_definitions",
    )
    op.drop_table("workflow_transition_definitions")
    op.drop_index(op.f("ix_workflow_states_profile_id"), table_name="workflow_states")
    op.drop_table("workflow_states")
    op.drop_index(op.f("ix_workflow_profiles_record_type"), table_name="workflow_profiles")
    op.drop_index("ix_workflow_profiles_record_lifecycle", table_name="workflow_profiles")
    op.drop_index(op.f("ix_workflow_profiles_lifecycle_status"), table_name="workflow_profiles")
    op.drop_index(op.f("ix_workflow_profiles_code"), table_name="workflow_profiles")
    op.drop_table("workflow_profiles")
    # ### end Alembic commands ###
