"""create master data and import tracking

Revision ID: 20260812_0002
Revises: 20260812_0001
Create Date: 2026-08-12 18:57:34.982190
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260812_0002"
down_revision: str | None = "20260812_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_categories",
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["cost_categories.id"],
            name=op.f("fk_cost_categories_parent_id_cost_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_categories")),
    )
    op.create_index(op.f("ix_cost_categories_code"), "cost_categories", ["code"], unique=True)
    op.create_index(
        op.f("ix_cost_categories_is_active"), "cost_categories", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_cost_categories_name"), "cost_categories", ["name"], unique=False)
    op.create_index(
        op.f("ix_cost_categories_parent_id"), "cost_categories", ["parent_id"], unique=False
    )
    op.create_table(
        "currencies",
        sa.Column("symbol", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currencies")),
    )
    op.create_index(op.f("ix_currencies_code"), "currencies", ["code"], unique=True)
    op.create_index(op.f("ix_currencies_is_active"), "currencies", ["is_active"], unique=False)
    op.create_index(op.f("ix_currencies_name"), "currencies", ["name"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("mapping_profile", sa.String(length=100), nullable=False),
        sa.Column("mapping_version", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("error_rows", sa.Integer(), nullable=False),
        sa.Column("imported_rows", sa.Integer(), nullable=False),
        sa.Column("staged_rows", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        "ix_import_batches_entity_status", "import_batches", ["entity_type", "status"], unique=False
    )
    op.create_index(
        op.f("ix_import_batches_entity_type"), "import_batches", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_import_batches_status"), "import_batches", ["status"], unique=False)
    op.create_table(
        "units",
        sa.Column("symbol", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
    )
    op.create_index(op.f("ix_units_code"), "units", ["code"], unique=True)
    op.create_index(op.f("ix_units_is_active"), "units", ["is_active"], unique=False)
    op.create_index(op.f("ix_units_name"), "units", ["name"], unique=False)
    op.create_table(
        "vendors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
    )
    op.create_index(op.f("ix_vendors_code"), "vendors", ["code"], unique=True)
    op.create_index(op.f("ix_vendors_is_active"), "vendors", ["is_active"], unique=False)
    op.create_index(op.f("ix_vendors_name"), "vendors", ["name"], unique=False)
    op.create_table(
        "cost_codes",
        sa.Column("cost_category_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cost_category_id"],
            ["cost_categories.id"],
            name=op.f("fk_cost_codes_cost_category_id_cost_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_codes")),
    )
    op.create_index(op.f("ix_cost_codes_code"), "cost_codes", ["code"], unique=True)
    op.create_index(
        op.f("ix_cost_codes_cost_category_id"), "cost_codes", ["cost_category_id"], unique=False
    )
    op.create_index(op.f("ix_cost_codes_is_active"), "cost_codes", ["is_active"], unique=False)
    op.create_index(op.f("ix_cost_codes_name"), "cost_codes", ["name"], unique=False)
    op.create_table(
        "import_errors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("column_name", sa.String(length=100), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("raw_value", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_errors_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_errors")),
    )
    op.create_index(op.f("ix_import_errors_batch_id"), "import_errors", ["batch_id"], unique=False)
    op.create_index(
        op.f("ix_import_errors_error_code"), "import_errors", ["error_code"], unique=False
    )
    op.create_table(
        "catalog_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("item_type", sa.String(length=30), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cost_category_id", sa.Uuid(), nullable=True),
        sa.Column("cost_code_id", sa.Uuid(), nullable=True),
        sa.Column("default_unit_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "item_type IN ('service','tangible','material','equipment')",
            name=op.f("ck_catalog_items_valid_item_type"),
        ),
        sa.ForeignKeyConstraint(
            ["cost_category_id"],
            ["cost_categories.id"],
            name=op.f("fk_catalog_items_cost_category_id_cost_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cost_code_id"],
            ["cost_codes.id"],
            name=op.f("fk_catalog_items_cost_code_id_cost_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["default_unit_id"],
            ["units.id"],
            name=op.f("fk_catalog_items_default_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_items")),
        sa.UniqueConstraint("item_type", "code", name="uq_catalog_items_type_code"),
    )
    op.create_index(op.f("ix_catalog_items_code"), "catalog_items", ["code"], unique=False)
    op.create_index(
        op.f("ix_catalog_items_cost_category_id"),
        "catalog_items",
        ["cost_category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_items_cost_code_id"), "catalog_items", ["cost_code_id"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_items_default_unit_id"), "catalog_items", ["default_unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_items_is_active"), "catalog_items", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_items_item_type"), "catalog_items", ["item_type"], unique=False
    )
    op.create_index(op.f("ix_catalog_items_name"), "catalog_items", ["name"], unique=False)
    op.create_table(
        "equipment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["catalog_items.id"],
            name=op.f("fk_equipment_id_catalog_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment")),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["catalog_items.id"],
            name=op.f("fk_materials_id_catalog_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
    )
    op.create_table(
        "rates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("currency_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_rates_non_negative_amount")),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_rates_valid_effective_range"),
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_rates_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["catalog_items.id"],
            name=op.f("fk_rates_item_id_catalog_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_rates_unit_id_units"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_rates_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rates")),
    )
    op.create_index(op.f("ix_rates_currency_id"), "rates", ["currency_id"], unique=False)
    op.create_index(op.f("ix_rates_effective_from"), "rates", ["effective_from"], unique=False)
    op.create_index(op.f("ix_rates_effective_to"), "rates", ["effective_to"], unique=False)
    op.create_index(op.f("ix_rates_is_active"), "rates", ["is_active"], unique=False)
    op.create_index(op.f("ix_rates_item_id"), "rates", ["item_id"], unique=False)
    op.create_index(op.f("ix_rates_unit_id"), "rates", ["unit_id"], unique=False)
    op.create_index(op.f("ix_rates_vendor_id"), "rates", ["vendor_id"], unique=False)
    op.create_table(
        "services",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["catalog_items.id"],
            name=op.f("fk_services_id_catalog_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_table(
        "tangibles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["catalog_items.id"],
            name=op.f("fk_tangibles_id_catalog_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tangibles")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tangibles")
    op.drop_table("services")
    op.drop_index(op.f("ix_rates_vendor_id"), table_name="rates")
    op.drop_index(op.f("ix_rates_unit_id"), table_name="rates")
    op.drop_index(op.f("ix_rates_item_id"), table_name="rates")
    op.drop_index(op.f("ix_rates_is_active"), table_name="rates")
    op.drop_index(op.f("ix_rates_effective_to"), table_name="rates")
    op.drop_index(op.f("ix_rates_effective_from"), table_name="rates")
    op.drop_index(op.f("ix_rates_currency_id"), table_name="rates")
    op.drop_table("rates")
    op.drop_table("materials")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_catalog_items_name"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_item_type"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_is_active"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_default_unit_id"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_cost_code_id"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_cost_category_id"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_code"), table_name="catalog_items")
    op.drop_table("catalog_items")
    op.drop_index(op.f("ix_import_errors_error_code"), table_name="import_errors")
    op.drop_index(op.f("ix_import_errors_batch_id"), table_name="import_errors")
    op.drop_table("import_errors")
    op.drop_index(op.f("ix_cost_codes_name"), table_name="cost_codes")
    op.drop_index(op.f("ix_cost_codes_is_active"), table_name="cost_codes")
    op.drop_index(op.f("ix_cost_codes_cost_category_id"), table_name="cost_codes")
    op.drop_index(op.f("ix_cost_codes_code"), table_name="cost_codes")
    op.drop_table("cost_codes")
    op.drop_index(op.f("ix_vendors_name"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_is_active"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_code"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(op.f("ix_units_name"), table_name="units")
    op.drop_index(op.f("ix_units_is_active"), table_name="units")
    op.drop_index(op.f("ix_units_code"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_import_batches_status"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_entity_type"), table_name="import_batches")
    op.drop_index("ix_import_batches_entity_status", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_currencies_name"), table_name="currencies")
    op.drop_index(op.f("ix_currencies_is_active"), table_name="currencies")
    op.drop_index(op.f("ix_currencies_code"), table_name="currencies")
    op.drop_table("currencies")
    op.drop_index(op.f("ix_cost_categories_parent_id"), table_name="cost_categories")
    op.drop_index(op.f("ix_cost_categories_name"), table_name="cost_categories")
    op.drop_index(op.f("ix_cost_categories_is_active"), table_name="cost_categories")
    op.drop_index(op.f("ix_cost_categories_code"), table_name="cost_categories")
    op.drop_table("cost_categories")
    # ### end Alembic commands ###
