"""create bulk cost build

Revision ID: 20260812_0004
Revises: 20260812_0003
Create Date: 2026-08-12 20:17:47.062959
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260812_0004"
down_revision: str | None = "20260812_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_estimates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("currency_id", sa.Uuid(), nullable=False),
        sa.Column("current_version_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currencies.id"],
            name=op.f("fk_cost_estimates_currency_id_currencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["well_requirements.id"],
            name=op.f("fk_cost_estimates_requirement_id_well_requirements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_estimates")),
    )
    op.create_index(op.f("ix_cost_estimates_code"), "cost_estimates", ["code"], unique=True)
    op.create_index(
        op.f("ix_cost_estimates_currency_id"), "cost_estimates", ["currency_id"], unique=False
    )
    op.create_index(
        op.f("ix_cost_estimates_requirement_id"), "cost_estimates", ["requirement_id"], unique=False
    )
    op.create_index(op.f("ix_cost_estimates_title"), "cost_estimates", ["title"], unique=False)
    op.create_table(
        "estimate_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("estimate_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default="pending_calculation", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft','pending_calculation')",
            name=op.f("ck_estimate_versions_valid_status"),
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_estimate_versions_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["estimate_id"],
            ["cost_estimates.id"],
            name=op.f("fk_estimate_versions_estimate_id_cost_estimates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate_versions")),
        sa.UniqueConstraint("estimate_id", "version_number", name="uq_estimate_versions_number"),
    )
    op.create_index(
        op.f("ix_estimate_versions_estimate_id"), "estimate_versions", ["estimate_id"], unique=False
    )
    op.create_index(
        op.f("ix_estimate_versions_status"), "estimate_versions", ["status"], unique=False
    )
    op.create_table(
        "estimate_assumptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("estimate_version_id", sa.Uuid(), nullable=False),
        sa.Column("cost_category_id", sa.Uuid(), nullable=True),
        sa.Column("contingency_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("escalation_percent", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "contingency_percent IS NULL OR contingency_percent >= 0",
            name=op.f("ck_estimate_assumptions_non_negative_contingency"),
        ),
        sa.CheckConstraint(
            "escalation_percent IS NULL OR escalation_percent >= 0",
            name=op.f("ck_estimate_assumptions_non_negative_escalation"),
        ),
        sa.ForeignKeyConstraint(
            ["cost_category_id"],
            ["cost_categories.id"],
            name=op.f("fk_estimate_assumptions_cost_category_id_cost_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            ["estimate_versions.id"],
            name=op.f("fk_estimate_assumptions_estimate_version_id_estimate_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate_assumptions")),
    )
    op.create_index(
        op.f("ix_estimate_assumptions_cost_category_id"),
        "estimate_assumptions",
        ["cost_category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_estimate_assumptions_estimate_version_id"),
        "estimate_assumptions",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_table(
        "estimate_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("estimate_version_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("requirement_item_id", sa.Uuid(), nullable=True),
        sa.Column("catalog_item_id", sa.Uuid(), nullable=False),
        sa.Column("cost_code_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("rate_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("base_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("contingency_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("escalation_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_estimate_items_non_negative_quantity")),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"],
            ["catalog_items.id"],
            name=op.f("fk_estimate_items_catalog_item_id_catalog_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cost_code_id"],
            ["cost_codes.id"],
            name=op.f("fk_estimate_items_cost_code_id_cost_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            ["estimate_versions.id"],
            name=op.f("fk_estimate_items_estimate_version_id_estimate_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rate_id"],
            ["rates.id"],
            name=op.f("fk_estimate_items_rate_id_rates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_item_id"],
            ["requirement_items.id"],
            name=op.f("fk_estimate_items_requirement_item_id_requirement_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_estimate_items_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_estimate_items_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate_items")),
        sa.UniqueConstraint(
            "estimate_version_id", "line_number", name="uq_estimate_items_version_line"
        ),
    )
    op.create_index(
        op.f("ix_estimate_items_catalog_item_id"),
        "estimate_items",
        ["catalog_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_estimate_items_cost_code_id"), "estimate_items", ["cost_code_id"], unique=False
    )
    op.create_index(
        op.f("ix_estimate_items_estimate_version_id"),
        "estimate_items",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_estimate_items_rate_id"), "estimate_items", ["rate_id"], unique=False)
    op.create_index(
        op.f("ix_estimate_items_requirement_item_id"),
        "estimate_items",
        ["requirement_item_id"],
        unique=False,
    )
    op.create_index(op.f("ix_estimate_items_unit_id"), "estimate_items", ["unit_id"], unique=False)
    op.create_index(
        op.f("ix_estimate_items_vendor_id"), "estimate_items", ["vendor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_estimate_items_vendor_id"), table_name="estimate_items")
    op.drop_index(op.f("ix_estimate_items_unit_id"), table_name="estimate_items")
    op.drop_index(op.f("ix_estimate_items_requirement_item_id"), table_name="estimate_items")
    op.drop_index(op.f("ix_estimate_items_rate_id"), table_name="estimate_items")
    op.drop_index(op.f("ix_estimate_items_estimate_version_id"), table_name="estimate_items")
    op.drop_index(op.f("ix_estimate_items_cost_code_id"), table_name="estimate_items")
    op.drop_index(op.f("ix_estimate_items_catalog_item_id"), table_name="estimate_items")
    op.drop_table("estimate_items")
    op.drop_index(
        op.f("ix_estimate_assumptions_estimate_version_id"), table_name="estimate_assumptions"
    )
    op.drop_index(
        op.f("ix_estimate_assumptions_cost_category_id"), table_name="estimate_assumptions"
    )
    op.drop_table("estimate_assumptions")
    op.drop_index(op.f("ix_estimate_versions_status"), table_name="estimate_versions")
    op.drop_index(op.f("ix_estimate_versions_estimate_id"), table_name="estimate_versions")
    op.drop_table("estimate_versions")
    op.drop_index(op.f("ix_cost_estimates_title"), table_name="cost_estimates")
    op.drop_index(op.f("ix_cost_estimates_requirement_id"), table_name="cost_estimates")
    op.drop_index(op.f("ix_cost_estimates_currency_id"), table_name="cost_estimates")
    op.drop_index(op.f("ix_cost_estimates_code"), table_name="cost_estimates")
    op.drop_table("cost_estimates")
    # ### end Alembic commands ###
