"""add calculation audit framework

Revision ID: 20260812_0005
Revises: 20260812_0004
Create Date: 2026-08-13 05:35:22.665270
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260812_0005"
down_revision: str | None = "20260812_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estimate_calculations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("estimate_version_id", sa.Uuid(), nullable=False),
        sa.Column("engine_version", sa.String(length=50), nullable=False),
        sa.Column("rule_set_version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("input_snapshot", sa.JSON(), nullable=True),
        sa.Column("output_snapshot", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('started','completed','blocked','failed')",
            name=op.f("ck_estimate_calculations_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            ["estimate_versions.id"],
            name=op.f("fk_estimate_calculations_estimate_version_id_estimate_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate_calculations")),
    )
    op.create_index(
        op.f("ix_estimate_calculations_estimate_version_id"),
        "estimate_calculations",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_estimate_calculations_status"), "estimate_calculations", ["status"], unique=False
    )
    op.create_index(
        "ix_estimate_calculations_version_created",
        "estimate_calculations",
        ["estimate_version_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "estimate_versions",
        sa.Column("base_total", sa.Numeric(precision=18, scale=4), nullable=True),
    )
    op.add_column(
        "estimate_versions",
        sa.Column("contingency_total", sa.Numeric(precision=18, scale=4), nullable=True),
    )
    op.add_column(
        "estimate_versions",
        sa.Column("escalation_total", sa.Numeric(precision=18, scale=4), nullable=True),
    )
    op.add_column(
        "estimate_versions",
        sa.Column("grand_total", sa.Numeric(precision=18, scale=4), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("estimate_versions", "grand_total")
    op.drop_column("estimate_versions", "escalation_total")
    op.drop_column("estimate_versions", "contingency_total")
    op.drop_column("estimate_versions", "base_total")
    op.drop_index("ix_estimate_calculations_version_created", table_name="estimate_calculations")
    op.drop_index(op.f("ix_estimate_calculations_status"), table_name="estimate_calculations")
    op.drop_index(
        op.f("ix_estimate_calculations_estimate_version_id"), table_name="estimate_calculations"
    )
    op.drop_table("estimate_calculations")
    # ### end Alembic commands ###
