"""add report export audit framework

Revision ID: 20260813_0009
Revises: 20260813_0008
Create Date: 2026-08-13 07:08:21.691497
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260813_0009"
down_revision: str | None = "20260813_0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_export_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_code", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("filters_snapshot", sa.JSON(), nullable=False),
        sa.Column("row_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('completed_shell','blocked','failed')",
            name=op.f("ck_report_export_attempts_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_export_attempts")),
    )
    op.create_index(
        op.f("ix_report_export_attempts_report_code"),
        "report_export_attempts",
        ["report_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_export_attempts_status"), "report_export_attempts", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_export_attempts_status"), table_name="report_export_attempts")
    op.drop_index(
        op.f("ix_report_export_attempts_report_code"), table_name="report_export_attempts"
    )
    op.drop_table("report_export_attempts")
    # ### end Alembic commands ###
