"""add cost control staging framework

Revision ID: 20260813_0008
Revises: 20260813_0007
Create Date: 2026-08-13 06:47:09.713102
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260813_0008"
down_revision: str | None = "20260813_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_control_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("estimate_version_id", sa.Uuid(), nullable=False),
        sa.Column("afe_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("cost_state", sa.String(length=30), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("file_sha256", sa.String(length=64), nullable=True),
        sa.Column("mapping_profile", sa.String(length=100), nullable=False),
        sa.Column("mapping_version", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column("valid_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column("posted_rows", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "cost_state IN ('field_estimate','commitment','accrual','actual','forecast')",
            name=op.f("ck_cost_control_batches_valid_cost_state"),
        ),
        sa.CheckConstraint(
            "source_type IN ('manual','excel')",
            name=op.f("ck_cost_control_batches_valid_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('invalid','validated','blocked','committed')",
            name=op.f("ck_cost_control_batches_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["afe_snapshot_id"],
            ["afe_snapshots.id"],
            name=op.f("fk_cost_control_batches_afe_snapshot_id_afe_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["estimate_version_id"],
            ["estimate_versions.id"],
            name=op.f("fk_cost_control_batches_estimate_version_id_estimate_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_control_batches")),
    )
    op.create_index(
        op.f("ix_cost_control_batches_afe_snapshot_id"),
        "cost_control_batches",
        ["afe_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_control_batches_cost_state"),
        "cost_control_batches",
        ["cost_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_control_batches_estimate_version_id"),
        "cost_control_batches",
        ["estimate_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_cost_control_batches_state_status",
        "cost_control_batches",
        ["cost_state", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_control_batches_status"), "cost_control_batches", ["status"], unique=False
    )
    op.create_table(
        "cost_control_batch_errors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("column_name", sa.String(length=100), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("raw_value", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["cost_control_batches.id"],
            name=op.f("fk_cost_control_batch_errors_batch_id_cost_control_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_control_batch_errors")),
    )
    op.create_index(
        op.f("ix_cost_control_batch_errors_batch_id"),
        "cost_control_batch_errors",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_control_batch_errors_error_code"),
        "cost_control_batch_errors",
        ["error_code"],
        unique=False,
    )
    op.create_table(
        "cost_control_post_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("policy_snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('completed','blocked','denied','failed')",
            name=op.f("ck_cost_control_post_attempts_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["cost_control_batches.id"],
            name=op.f("fk_cost_control_post_attempts_batch_id_cost_control_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_control_post_attempts")),
    )
    op.create_index(
        "ix_cost_control_post_attempts_batch_created",
        "cost_control_post_attempts",
        ["batch_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_control_post_attempts_batch_id"),
        "cost_control_post_attempts",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_control_post_attempts_status"),
        "cost_control_post_attempts",
        ["status"],
        unique=False,
    )
    op.create_table(
        "cost_control_staged_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("source_document_type", sa.String(length=50), nullable=False),
        sa.Column("source_document_reference", sa.String(length=150), nullable=False),
        sa.Column("external_transaction_id", sa.String(length=150), nullable=True),
        sa.Column("cost_code", sa.String(length=100), nullable=False),
        sa.Column("vendor_code", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("unit_code", sa.String(length=50), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "correction_kind", sa.String(length=20), server_default="original", nullable=False
        ),
        sa.Column("reverses_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("raw_snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "correction_kind IN ('original','reversal','adjustment')",
            name=op.f("ck_cost_control_staged_lines_valid_correction_kind"),
        ),
        sa.CheckConstraint(
            "row_number >= 1", name=op.f("ck_cost_control_staged_lines_positive_row_number")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["cost_control_batches.id"],
            name=op.f("fk_cost_control_staged_lines_batch_id_cost_control_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_control_staged_lines")),
        sa.UniqueConstraint("batch_id", "row_number", name="uq_cost_control_staged_batch_row"),
    )
    op.create_index(
        op.f("ix_cost_control_staged_lines_batch_id"),
        "cost_control_staged_lines",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_control_staged_lines_cost_code"),
        "cost_control_staged_lines",
        ["cost_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_control_staged_lines_vendor_code"),
        "cost_control_staged_lines",
        ["vendor_code"],
        unique=False,
    )
    op.create_table(
        "cost_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("posting_reference", sa.String(length=150), nullable=False),
        sa.Column("afe_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("source_batch_id", sa.Uuid(), nullable=False),
        sa.Column("source_staged_line_id", sa.Uuid(), nullable=False),
        sa.Column("cost_state", sa.String(length=30), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("source_document_type", sa.String(length=50), nullable=False),
        sa.Column("source_document_reference", sa.String(length=150), nullable=False),
        sa.Column("external_transaction_id", sa.String(length=150), nullable=True),
        sa.Column("cost_code", sa.String(length=100), nullable=False),
        sa.Column("vendor_code", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("unit_code", sa.String(length=50), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("correction_kind", sa.String(length=20), nullable=False),
        sa.Column("reverses_transaction_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "correction_kind IN ('original','reversal','adjustment')",
            name=op.f("ck_cost_transactions_valid_correction_kind"),
        ),
        sa.CheckConstraint(
            "cost_state IN ('field_estimate','commitment','accrual','actual','forecast')",
            name=op.f("ck_cost_transactions_valid_cost_state"),
        ),
        sa.ForeignKeyConstraint(
            ["afe_snapshot_id"],
            ["afe_snapshots.id"],
            name=op.f("fk_cost_transactions_afe_snapshot_id_afe_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reverses_transaction_id"],
            ["cost_transactions.id"],
            name=op.f("fk_cost_transactions_reverses_transaction_id_cost_transactions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_batch_id"],
            ["cost_control_batches.id"],
            name=op.f("fk_cost_transactions_source_batch_id_cost_control_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_staged_line_id"],
            ["cost_control_staged_lines.id"],
            name=op.f("fk_cost_transactions_source_staged_line_id_cost_control_staged_lines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_transactions")),
    )
    op.create_index(
        op.f("ix_cost_transactions_afe_snapshot_id"),
        "cost_transactions",
        ["afe_snapshot_id"],
        unique=False,
    )
    op.create_index(
        "ix_cost_transactions_afe_state_date",
        "cost_transactions",
        ["afe_snapshot_id", "cost_state", "transaction_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_transactions_cost_code"), "cost_transactions", ["cost_code"], unique=False
    )
    op.create_index(
        op.f("ix_cost_transactions_cost_state"), "cost_transactions", ["cost_state"], unique=False
    )
    op.create_index(
        op.f("ix_cost_transactions_external_transaction_id"),
        "cost_transactions",
        ["external_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_transactions_posting_reference"),
        "cost_transactions",
        ["posting_reference"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cost_transactions_reverses_transaction_id"),
        "cost_transactions",
        ["reverses_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_transactions_source_batch_id"),
        "cost_transactions",
        ["source_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_transactions_source_document_reference"),
        "cost_transactions",
        ["source_document_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_transactions_source_staged_line_id"),
        "cost_transactions",
        ["source_staged_line_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cost_transactions_transaction_date"),
        "cost_transactions",
        ["transaction_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_transactions_vendor_code"), "cost_transactions", ["vendor_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cost_transactions_vendor_code"), table_name="cost_transactions")
    op.drop_index(op.f("ix_cost_transactions_transaction_date"), table_name="cost_transactions")
    op.drop_index(
        op.f("ix_cost_transactions_source_staged_line_id"), table_name="cost_transactions"
    )
    op.drop_index(
        op.f("ix_cost_transactions_source_document_reference"), table_name="cost_transactions"
    )
    op.drop_index(op.f("ix_cost_transactions_source_batch_id"), table_name="cost_transactions")
    op.drop_index(
        op.f("ix_cost_transactions_reverses_transaction_id"), table_name="cost_transactions"
    )
    op.drop_index(op.f("ix_cost_transactions_posting_reference"), table_name="cost_transactions")
    op.drop_index(
        op.f("ix_cost_transactions_external_transaction_id"), table_name="cost_transactions"
    )
    op.drop_index(op.f("ix_cost_transactions_cost_state"), table_name="cost_transactions")
    op.drop_index(op.f("ix_cost_transactions_cost_code"), table_name="cost_transactions")
    op.drop_index("ix_cost_transactions_afe_state_date", table_name="cost_transactions")
    op.drop_index(op.f("ix_cost_transactions_afe_snapshot_id"), table_name="cost_transactions")
    op.drop_table("cost_transactions")
    op.drop_index(
        op.f("ix_cost_control_staged_lines_vendor_code"), table_name="cost_control_staged_lines"
    )
    op.drop_index(
        op.f("ix_cost_control_staged_lines_cost_code"), table_name="cost_control_staged_lines"
    )
    op.drop_index(
        op.f("ix_cost_control_staged_lines_batch_id"), table_name="cost_control_staged_lines"
    )
    op.drop_table("cost_control_staged_lines")
    op.drop_index(
        op.f("ix_cost_control_post_attempts_status"), table_name="cost_control_post_attempts"
    )
    op.drop_index(
        op.f("ix_cost_control_post_attempts_batch_id"), table_name="cost_control_post_attempts"
    )
    op.drop_index(
        "ix_cost_control_post_attempts_batch_created", table_name="cost_control_post_attempts"
    )
    op.drop_table("cost_control_post_attempts")
    op.drop_index(
        op.f("ix_cost_control_batch_errors_error_code"), table_name="cost_control_batch_errors"
    )
    op.drop_index(
        op.f("ix_cost_control_batch_errors_batch_id"), table_name="cost_control_batch_errors"
    )
    op.drop_table("cost_control_batch_errors")
    op.drop_index(op.f("ix_cost_control_batches_status"), table_name="cost_control_batches")
    op.drop_index("ix_cost_control_batches_state_status", table_name="cost_control_batches")
    op.drop_index(
        op.f("ix_cost_control_batches_estimate_version_id"), table_name="cost_control_batches"
    )
    op.drop_index(op.f("ix_cost_control_batches_cost_state"), table_name="cost_control_batches")
    op.drop_index(
        op.f("ix_cost_control_batches_afe_snapshot_id"), table_name="cost_control_batches"
    )
    op.drop_table("cost_control_batches")
    # ### end Alembic commands ###
