"""create requirement intake

Revision ID: 20260812_0003
Revises: 20260812_0002
Create Date: 2026-08-12 19:47:37.754286
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260812_0003"
down_revision: str | None = "20260812_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_code"), "projects", ["code"], unique=True)
    op.create_index(op.f("ix_projects_is_active"), "projects", ["is_active"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_table(
        "wells",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_wells_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wells")),
        sa.UniqueConstraint("project_id", "code", name="uq_wells_project_code"),
    )
    op.create_index(op.f("ix_wells_code"), "wells", ["code"], unique=False)
    op.create_index(op.f("ix_wells_is_active"), "wells", ["is_active"], unique=False)
    op.create_index(op.f("ix_wells_name"), "wells", ["name"], unique=False)
    op.create_index(op.f("ix_wells_project_id"), "wells", ["project_id"], unique=False)
    op.create_table(
        "well_requirements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("well_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="draft", nullable=False),
        sa.Column("revision_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft','submitted')", name=op.f("ck_well_requirements_valid_status")
        ),
        sa.CheckConstraint(
            "revision_number >= 1", name=op.f("ck_well_requirements_positive_revision")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["well_requirements.id"],
            name=op.f("fk_well_requirements_supersedes_id_well_requirements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells.id"],
            name=op.f("fk_well_requirements_well_id_wells"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_well_requirements")),
        sa.UniqueConstraint(
            "well_id", "code", "revision_number", name="uq_requirements_well_code_revision"
        ),
    )
    op.create_index(op.f("ix_well_requirements_code"), "well_requirements", ["code"], unique=False)
    op.create_index(
        op.f("ix_well_requirements_is_active"), "well_requirements", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_well_requirements_status"), "well_requirements", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_well_requirements_supersedes_id"),
        "well_requirements",
        ["supersedes_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_well_requirements_title"), "well_requirements", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_well_requirements_well_id"), "well_requirements", ["well_id"], unique=False
    )
    op.create_table(
        "requirement_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("catalog_item_id", sa.Uuid(), nullable=False),
        sa.Column("cost_code_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("section_name", sa.String(length=150), nullable=True),
        sa.Column("planned_duration_days", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("planned_depth_from", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("planned_depth_to", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("depth_unit_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "line_number >= 1", name=op.f("ck_requirement_items_positive_line_number")
        ),
        sa.CheckConstraint(
            "planned_depth_from IS NULL OR planned_depth_to IS NULL OR planned_depth_to >= planned_depth_from",
            name=op.f("ck_requirement_items_valid_depth_range"),
        ),
        sa.CheckConstraint(
            "planned_duration_days IS NULL OR planned_duration_days >= 0",
            name=op.f("ck_requirement_items_non_negative_duration"),
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_requirement_items_non_negative_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"],
            ["catalog_items.id"],
            name=op.f("fk_requirement_items_catalog_item_id_catalog_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cost_code_id"],
            ["cost_codes.id"],
            name=op.f("fk_requirement_items_cost_code_id_cost_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["depth_unit_id"],
            ["units.id"],
            name=op.f("fk_requirement_items_depth_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["well_requirements.id"],
            name=op.f("fk_requirement_items_requirement_id_well_requirements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_requirement_items_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_items")),
        sa.UniqueConstraint(
            "requirement_id", "line_number", name="uq_requirement_items_requirement_line"
        ),
    )
    op.create_index(
        op.f("ix_requirement_items_catalog_item_id"),
        "requirement_items",
        ["catalog_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirement_items_cost_code_id"),
        "requirement_items",
        ["cost_code_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirement_items_depth_unit_id"),
        "requirement_items",
        ["depth_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirement_items_is_active"), "requirement_items", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_requirement_items_requirement_id"),
        "requirement_items",
        ["requirement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirement_items_section_name"),
        "requirement_items",
        ["section_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirement_items_unit_id"), "requirement_items", ["unit_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requirement_items_unit_id"), table_name="requirement_items")
    op.drop_index(op.f("ix_requirement_items_section_name"), table_name="requirement_items")
    op.drop_index(op.f("ix_requirement_items_requirement_id"), table_name="requirement_items")
    op.drop_index(op.f("ix_requirement_items_is_active"), table_name="requirement_items")
    op.drop_index(op.f("ix_requirement_items_depth_unit_id"), table_name="requirement_items")
    op.drop_index(op.f("ix_requirement_items_cost_code_id"), table_name="requirement_items")
    op.drop_index(op.f("ix_requirement_items_catalog_item_id"), table_name="requirement_items")
    op.drop_table("requirement_items")
    op.drop_index(op.f("ix_well_requirements_well_id"), table_name="well_requirements")
    op.drop_index(op.f("ix_well_requirements_title"), table_name="well_requirements")
    op.drop_index(op.f("ix_well_requirements_supersedes_id"), table_name="well_requirements")
    op.drop_index(op.f("ix_well_requirements_status"), table_name="well_requirements")
    op.drop_index(op.f("ix_well_requirements_is_active"), table_name="well_requirements")
    op.drop_index(op.f("ix_well_requirements_code"), table_name="well_requirements")
    op.drop_table("well_requirements")
    op.drop_index(op.f("ix_wells_project_id"), table_name="wells")
    op.drop_index(op.f("ix_wells_name"), table_name="wells")
    op.drop_index(op.f("ix_wells_is_active"), table_name="wells")
    op.drop_index(op.f("ix_wells_code"), table_name="wells")
    op.drop_table("wells")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_is_active"), table_name="projects")
    op.drop_index(op.f("ix_projects_code"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
