"""add enterprise configuration foundation

Revision ID: 20260813_0011
Revises: 20260813_0010
Create Date: 2026-08-13 08:07:31.230201
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260813_0011"
down_revision: str | None = "20260813_0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_breakdown_structures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("lifecycle_status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft','published','retired')",
            name=op.f("ck_cost_breakdown_structures_valid_lifecycle"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_breakdown_structures")),
        sa.UniqueConstraint("code", "version_number", name="uq_cost_breakdown_structure_version"),
    )
    op.create_index(
        op.f("ix_cost_breakdown_structures_code"),
        "cost_breakdown_structures",
        ["code"],
        unique=False,
    )
    op.create_table(
        "enterprise_node_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("level_order", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enterprise_node_types")),
    )
    op.create_index(
        op.f("ix_enterprise_node_types_code"), "enterprise_node_types", ["code"], unique=True
    )
    op.create_table(
        "estimate_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("lifecycle_status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft','published','retired')",
            name=op.f("ck_estimate_templates_valid_lifecycle"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate_templates")),
        sa.UniqueConstraint("code", "version_number", name="uq_estimate_template_version"),
    )
    op.create_index(
        op.f("ix_estimate_templates_code"), "estimate_templates", ["code"], unique=False
    )
    op.create_table(
        "rate_books",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("lifecycle_status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft','published','retired')",
            name=op.f("ck_rate_books_valid_lifecycle"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_books")),
        sa.UniqueConstraint("code", "version_number", name="uq_rate_book_version"),
    )
    op.create_index(op.f("ix_rate_books_code"), "rate_books", ["code"], unique=False)
    op.create_table(
        "reporting_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_system", sa.String(length=100), nullable=False),
        sa.Column("source_dimension", sa.String(length=100), nullable=False),
        sa.Column("source_value", sa.String(length=200), nullable=False),
        sa.Column("target_value", sa.String(length=200), nullable=False),
        sa.Column("version_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("lifecycle_status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "lifecycle_status IN ('draft','published','retired')",
            name=op.f("ck_reporting_mappings_valid_lifecycle"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reporting_mappings")),
        sa.UniqueConstraint(
            "target_system",
            "source_dimension",
            "source_value",
            "version_number",
            name="uq_reporting_mapping_version",
        ),
    )
    op.create_index(
        op.f("ix_reporting_mappings_target_system"),
        "reporting_mappings",
        ["target_system"],
        unique=False,
    )
    op.create_table(
        "enterprise_hierarchy_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_type_id", sa.Uuid(), nullable=False),
        sa.Column("child_type_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_type_id"],
            ["enterprise_node_types.id"],
            name=op.f("fk_enterprise_hierarchy_rules_child_type_id_enterprise_node_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_type_id"],
            ["enterprise_node_types.id"],
            name=op.f("fk_enterprise_hierarchy_rules_parent_type_id_enterprise_node_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enterprise_hierarchy_rules")),
        sa.UniqueConstraint("parent_type_id", "child_type_id", name="uq_enterprise_hierarchy_rule"),
    )
    op.create_index(
        op.f("ix_enterprise_hierarchy_rules_child_type_id"),
        "enterprise_hierarchy_rules",
        ["child_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enterprise_hierarchy_rules_parent_type_id"),
        "enterprise_hierarchy_rules",
        ["parent_type_id"],
        unique=False,
    )
    op.create_table(
        "enterprise_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("node_type_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_type_id"],
            ["enterprise_node_types.id"],
            name=op.f("fk_enterprise_nodes_node_type_id_enterprise_node_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["enterprise_nodes.id"],
            name=op.f("fk_enterprise_nodes_parent_id_enterprise_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enterprise_nodes")),
    )
    op.create_index(op.f("ix_enterprise_nodes_code"), "enterprise_nodes", ["code"], unique=True)
    op.create_index(
        op.f("ix_enterprise_nodes_node_type_id"), "enterprise_nodes", ["node_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_enterprise_nodes_parent_id"), "enterprise_nodes", ["parent_id"], unique=False
    )
    op.create_table(
        "cost_breakdown_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("structure_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_category_id", sa.Uuid(), nullable=True),
        sa.Column("cost_code_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cost_category_id"],
            ["cost_categories.id"],
            name=op.f("fk_cost_breakdown_nodes_cost_category_id_cost_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cost_code_id"],
            ["cost_codes.id"],
            name=op.f("fk_cost_breakdown_nodes_cost_code_id_cost_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["cost_breakdown_nodes.id"],
            name=op.f("fk_cost_breakdown_nodes_parent_id_cost_breakdown_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["cost_breakdown_structures.id"],
            name=op.f("fk_cost_breakdown_nodes_structure_id_cost_breakdown_structures"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_breakdown_nodes")),
        sa.UniqueConstraint("structure_id", "code", name="uq_cost_breakdown_node_code"),
    )
    op.create_index(
        op.f("ix_cost_breakdown_nodes_parent_id"),
        "cost_breakdown_nodes",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_breakdown_nodes_structure_id"),
        "cost_breakdown_nodes",
        ["structure_id"],
        unique=False,
    )
    op.create_table(
        "estimate_template_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("catalog_item_id", sa.Uuid(), nullable=False),
        sa.Column("cost_code_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("default_quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("is_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["catalog_item_id"],
            ["catalog_items.id"],
            name=op.f("fk_estimate_template_lines_catalog_item_id_catalog_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cost_code_id"],
            ["cost_codes.id"],
            name=op.f("fk_estimate_template_lines_cost_code_id_cost_codes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["estimate_templates.id"],
            name=op.f("fk_estimate_template_lines_template_id_estimate_templates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_estimate_template_lines_unit_id_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate_template_lines")),
        sa.UniqueConstraint("template_id", "line_number", name="uq_estimate_template_line"),
    )
    op.create_index(
        op.f("ix_estimate_template_lines_template_id"),
        "estimate_template_lines",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "rate_book_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rate_book_id", sa.Uuid(), nullable=False),
        sa.Column("rate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rate_book_id"],
            ["rate_books.id"],
            name=op.f("fk_rate_book_entries_rate_book_id_rate_books"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rate_id"],
            ["rates.id"],
            name=op.f("fk_rate_book_entries_rate_id_rates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_book_entries")),
        sa.UniqueConstraint("rate_book_id", "rate_id", name="uq_rate_book_entry"),
    )
    op.create_index(
        op.f("ix_rate_book_entries_rate_book_id"),
        "rate_book_entries",
        ["rate_book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rate_book_entries_rate_id"), "rate_book_entries", ["rate_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rate_book_entries_rate_id"), table_name="rate_book_entries")
    op.drop_index(op.f("ix_rate_book_entries_rate_book_id"), table_name="rate_book_entries")
    op.drop_table("rate_book_entries")
    op.drop_index(
        op.f("ix_estimate_template_lines_template_id"), table_name="estimate_template_lines"
    )
    op.drop_table("estimate_template_lines")
    op.drop_index(op.f("ix_cost_breakdown_nodes_structure_id"), table_name="cost_breakdown_nodes")
    op.drop_index(op.f("ix_cost_breakdown_nodes_parent_id"), table_name="cost_breakdown_nodes")
    op.drop_table("cost_breakdown_nodes")
    op.drop_index(op.f("ix_enterprise_nodes_parent_id"), table_name="enterprise_nodes")
    op.drop_index(op.f("ix_enterprise_nodes_node_type_id"), table_name="enterprise_nodes")
    op.drop_index(op.f("ix_enterprise_nodes_code"), table_name="enterprise_nodes")
    op.drop_table("enterprise_nodes")
    op.drop_index(
        op.f("ix_enterprise_hierarchy_rules_parent_type_id"),
        table_name="enterprise_hierarchy_rules",
    )
    op.drop_index(
        op.f("ix_enterprise_hierarchy_rules_child_type_id"), table_name="enterprise_hierarchy_rules"
    )
    op.drop_table("enterprise_hierarchy_rules")
    op.drop_index(op.f("ix_reporting_mappings_target_system"), table_name="reporting_mappings")
    op.drop_table("reporting_mappings")
    op.drop_index(op.f("ix_rate_books_code"), table_name="rate_books")
    op.drop_table("rate_books")
    op.drop_index(op.f("ix_estimate_templates_code"), table_name="estimate_templates")
    op.drop_table("estimate_templates")
    op.drop_index(op.f("ix_enterprise_node_types_code"), table_name="enterprise_node_types")
    op.drop_table("enterprise_node_types")
    op.drop_index(op.f("ix_cost_breakdown_structures_code"), table_name="cost_breakdown_structures")
    op.drop_table("cost_breakdown_structures")
    # ### end Alembic commands ###
